[features]
seeds = false
skip-lint = false
[programs.localnet]
mixarcade_solana = "5kDHrYTjDZ19d8jdj1RoVjomjLoAYK2XQPeBfZdFFMFL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/recepcnky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
